= Monitor PVC Disk Usage

== Overview

{product} exposes `kubelet` metrics that can be used to monitor PVC disk usage.

The following volume metrics are available:

[source]
----
kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_used_bytes

kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
----

== Prerequisites

* Command Line Access to {product}

== Create a Disk Usage Alert

The following instructions create two alerts that trigger when the disk usage or used https://en.wikipedia.org/wiki/Inode[inodes] of any PVC in the given namespace exceed 90%.

. Set the namespace your application is running in
+
[source,bash]
----
APP_NAMESPACE="my-app"
----

. Create the alert
+
[source,shell]
----
kubectl -n "${APP_NAMESPACE}" apply -f - <<YAML
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-app-volume-alerts
spec:
  groups:
  - name: my-app-volume.rules
    rules:
    - alert: VolumeAvailableSpaceLow
      expr: |
        (
          sum(kubelet_volume_stats_available_bytes{persistentvolumeclaim!=""}) by (persistentvolumeclaim)
        /
          sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim!=""}) by (persistentvolumeclaim)
        ) < 0.1 <1>
      for: 5m
      labels:
        severity: critical <2>
      annotations:
        summary: "PVC available space low"
        description: |
          PVC {{ \$labels.persistentvolumeclaim }} available space {{ \$value | humanizePercentage }} is low.

          Your application may become unable to write data to disk.

          Either increase the PVC size or delete files to free up space.
    - alert: VolumeFreeInodesLow
      expr: |
        (
          sum(
            kubelet_volume_stats_inodes_free{persistentvolumeclaim!=""} * on(persistentvolumeclaim) kube_persistentvolumeclaim_info{storageclass!="cephfs-fspool-cluster"} <3>
          ) by (persistentvolumeclaim)
        /
          sum(
            kubelet_volume_stats_inodes{persistentvolumeclaim!=""} * on(persistentvolumeclaim) kube_persistentvolumeclaim_info{storageclass!="cephfs-fspool-cluster"}
          ) by (persistentvolumeclaim)
        ) < 0.1 <4>
      for: 5m
      labels:
        severity: critical <2>
      annotations:
        summary: "PVC free inodes low"
        description: |
          PVC {{ \$labels.persistentvolumeclaim }} free inodes {{ \$value | humanizePercentage }} is low.

          Your application may become unable to create new files and directories.

          Inodes are used to track files and directories. When the number of inodes is low, you may not be able to create new files or directories.
          A high inode usage may stem from many small files. Increasing the PVC size will scale up inodes proportionally.

          Either increase the PVC size or delete files to free up inodes.
YAML
----
<1> Alert if available space is less than 10%.
<2> You might want to add a higher threshold with a `warning` severity.
<3> CephFS doesn't store metadata in inode structures and always reports zero free inodes.
This filter excludes CephFS PVCs from the alert.
<4> Alert if free inodes are less than 10%.
+
[TIP]
====
It's possible to alert on absolute values, for example if the available space is less than 10GiB.

[source,yaml]
----
expr: |
  kubelet_volume_stats_available_bytes{persistentvolumeclaim!=""} < 10 * 1024 * 1024 * 1024
annotations:
  description: |
    PVC {{ $labels.persistentvolumeclaim }} available space {{ $value | humanize1024 }} is low.

    ...
----
====
