= Organizations and RBAC

Each OpenShift Project (Kubernetes Namespace) belongs to an organization, indicated by the label `appuio.io/organization` on the `Namespace` and `Project` objects.

The organization is also reflected as a `Group` object in the {zone} and is used to assign default RBAC rules.

== Default RBAC rules

A `RoleBinding` with the name `admin` is created in the `Namespace` which grants the creator the `ClusterRole` called `admin`.
Another `RoleBinding` with the name `organization-admin` is created in the `Namespace` which also grants the organization `admin` cluster role.
The user is free to modify or delete either.

IMPORTANT: Be sure to not lock yourself out!

== Organization Membership

On the first login to {idp} the default organization membership is assigned.

Membership of organizations and organizations itself are currently being maintained by VSHN.

It's planned to enable self-management of organizations and membership in the https://roadmap.appuio.cloud[upcoming Webportal].
Please xref:contact[contact] us to manage organization membership for you for the time being.
