= Application Demo: Ghost Blog
:app-link: https://ghost.org/[Ghost^]
:app-logo: ghost-blog.png

include::partial$app-demo-partials.adoc[tag=introduction]

include::partial$app-demo-partials.adoc[tag=requirements]

== About the Application

> Ghost is a powerful app for new-media creators to publish, share, and grow a business around their content. It comes with modern tools to build a website, publish content, send newsletters & offer paid subscriptions to members.

include::partial$app-demo-partials.adoc[tag=step1]

== Step 2: Deploy the application

To deploy the application we will use standard Kubernetes objects.
Save the example YAML Kubernetes resources into a file and apply it with `oc apply -f <myfile.yaml>`.

. First, we need a database:
+
.Database ordering from the VSHN Application Catalog
[source,yaml]
----
include::example$example-app-exo-mysql.yaml[]
----
+
This will create a MySQL DBaaS instance with default settings.
See https://docs.appcat.ch/exoscale-dbaas/mysql/index.html[the AppCat docs^] for more information.

. Then we deploy the application:
+
.Application deployment with all other needed resources
[source,yaml]
----
include::example$example-app-ghost.yaml[]
---
include::example$example-app-service.yaml[]
---
include::example$example-app-pvc.yaml[]
---
include::example$example-app-route.yaml[]
----

. Now wait until your pod appears with the status "Running":
+
[source,shell]
--
oc get pods --watch
--

. Last but not least retrieve the URL of your Ghost blog:
+
[source,shell]
--
oc get route example-app -o jsonpath='{.spec.host}'
--

You can now login to your Ghost instance on `/ghost` with the default credentials by the image:

* Username: \user@example.com
* Password: bitnami123

include::partial$app-demo-partials.adoc[tag=whats-next]

Especially for this example application:

* Change the default username and password immediately.
* Review the https://github.com/bitnami/containers/blob/main/bitnami/ghost/README.md[documentation of the used image^] to learn more about the configuration and possibilities.
* Ghost needs a proper mail sending configuration in production, we recommend using a managed mail sending service for that, for example https://www.mailgun.com/[Mailgun^].

include::partial$app-demo-partials.adoc[tag=cleanup]

include::partial$app-demo-partials.adoc[tag=contactus]
