= Application Demo: Ghost Blog
:app-link: https://ghost.org/[Ghost^]
:app-logo: ghost-blog.png

include::partial$app-demo-partials.adoc[tag=introduction]

include::partial$app-demo-partials.adoc[tag=requirements]

== About the Application

> Ghost is a powerful app for new-media creators to publish, share, and grow a business around their content. It comes with modern tools to build a website, publish content, send newsletters & offer paid subscriptions to members.

include::partial$app-demo-partials.adoc[tag=step1]

== Step 2: Deploy the application

To deploy the application we will use standard Kubernetes objects.
Save the example YAML Kubernetes resources into a file and apply it with `oc apply -f <myfile.yaml>`.

. First, we need a database:
+
.Database ordering from the VSHN Application Catalog
[source,yaml]
----
include::example$example-app-exo-mysql.yaml[]
----
+
This will create a MySQL DBaaS instance with default settings.
See xref:appcat:ROOT:exoscale-dbaas/mysql/create.adoc[the AppCat docs] for more information.

. Second, we create an OpenShift route to get the generated URL (required in a following step to configure Ghost)
+
.Route for the example application
[source,yaml]
----
include::example$example-app-route.yaml[]
----

. Now we need to get the generated URL:
+
[source,shell]
----
oc get route example-app -o jsonpath='{.spec.host}'
----

. Update the environment variable `url` in the following YAML with the generated URL you retrieved in the previous step and apply the result to the cluster:
+
.Application deployment with all other needed resources
[source,yaml]
----
include::example$example-app-ghost.yaml[]
----

. Now wait until your pod appears with the status "Running":
+
[source,shell]
--
oc get pods --watch
--

You can now access your Ghost blog with the URL you retrieved in step 3.

include::partial$app-demo-partials.adoc[tag=whats-next]

Especially for this example application:

* Review the https://ghost.org/docs/[official Ghost documentation^] to learn more about the configuration and possibilities.
* Ghost needs a proper mail sending configuration in production, we recommend using a managed mail sending service for that, for example https://www.mailgun.com/[Mailgun^].
* Secure the database connection to use TLS encryption. This is described in the https://ghost.org/docs/config/#database[Ghost documentation]. You can find the CA certificate in the database secret:
+
[source,shell]
----
oc get secret mysql-creds -o jsonpath='{.data.ca\.crt}' | base64 -d
----

include::partial$app-demo-partials.adoc[tag=cleanup]
