= Application Demo: Gitea or Forgejo
:app-link: https://www.gitea.io/[Gitea^] or https://forgejo.org/[Forgejo^]
:app-logo: gitea.svg

include::partial$app-demo-partials.adoc[tag=introduction]

include::partial$app-demo-partials.adoc[tag=requirements]

== About the Application

> Gitea - Git with a cup of tea
>
> A painless self-hosted Git service.
> 
> Gitea is a community managed lightweight code hosting solution written in Go. It is published under the MIT license.

> Forgejo - Beyond coding. We forge.
> 
> Forgejo is a self-hosted lightweight software forge.
> Easy to install and low maintenance, it just does the job.
> Brought to you by an inclusive community under the umbrella of Codeberg e.V., a democratic non-profit organization, Forgejo can be trusted to be exclusively Free Software. It is a "soft" fork of Gitea with a focus on scaling, federation and privacy. 

include::partial$app-demo-partials.adoc[tag=step1]

== Step 2: Deploy the application

To deploy the application we will use standard Kubernetes objects.
Save the example YAML Kubernetes resources into a file and apply it with `oc apply -f <myfile.yaml>`.

. First, we need a database:
+
.Database ordering from the VSHN Application Catalog
[source,yaml]
----
include::example$example-app-exo-mysql.yaml[]
----
+
This will create a MySQL DBaaS instance with default settings.
See xref:appcat:ROOT:exoscale-dbaas/mysql/create.adoc[the AppCat docs] for more information.

. Then we deploy the application:
+
.Application deployment with all other needed resources
[source,yaml]
----
include::example$example-app-gitea.yaml[]
---
include::example$example-app-service.yaml[]
---
include::example$example-app-pvc.yaml[]
---
include::example$example-app-route.yaml[]
----

. Now wait until your pod appears with the status "Running":
+
[source,shell]
--
oc get pods --watch
--

. Last but not least retrieve the URL of your Gitea or Forgejo instance:
+
[source,shell]
--
oc get route example-app -o jsonpath='{.spec.host}'
--

You can now login to your Odoo instance with the default credentials by the image:

* Username: \user@example.com
* Password: bitnami

include::partial$app-demo-partials.adoc[tag=whats-next]

Especially for this example application:

* Change the default username and password immediately.
* Review the https://github.com/bitnami/containers/blob/main/bitnami/odoo/README.md[documentation of the used image^] to learn more about the configuration and possibilities.
* Odoo needs a proper mail sending configuration in production, we recommend using a managed mail sending service for that, for example https://www.mailgun.com/[Mailgun^].

include::partial$app-demo-partials.adoc[tag=cleanup]
