= Node Classes

Some zones of {product} provide a set of two more node classes.
A node class is a group of nodes having a distinct set of specidifications.
Those nodes can be optimized for compute, memory or cost or they could offer special features like GPU support.

The node classes available on a zone are indicated on the https://portal.appuio.cloud/zones[zone listing].

See xref:how-to/choose-node-class.adoc[] on how to schedule your workload on a specific node class.

You will find the characteristics of all node class explained below.


flex::
+
Flex nodes directly map to https://www.cloudscale.ch/en/pricing#flavors-explained[flex instances defined by the infrastrucutre provider].
They use CPUs shared with other instances.
This allows for short term load peaks but can occasionally require your workload to wait for CPU time.
Workload running on flex nodes will cost you less (see https://products.docs.vshn.ch/products/appuio/cloud/pricing_2022-12-01.html[pricing]).
+
Use this node class for your background jobs, test environments or applications not sensitive to latency.
+
On an {product} zone running on cloudscale.ch, your workload will by default be scheduled on flex nodes.

plus::
+
Flex nodes directly map to https://www.cloudscale.ch/en/pricing#flavors-explained[plus instances defined by the infrastrucutre provider].
Plus nodes have dedicated CPU cores.
This gives you consistent performance but will cost you more (see https://products.docs.vshn.ch/products/appuio/cloud/pricing_2022-12-01.html[pricing]).
+
The plus node class is probably the right choise for your production frontends, database and other applications sensitive to latency.

