= Node Classes

Some zones of {product} provide a set of two more node classes.
A node class is a group of nodes having a distinct set of specifications.
Those nodes can be optimized for compute, memory, or cost, or they could offer special features like GPU support.

The node classes available on a zone are indicated on https://portal.appuio.cloud/zones[the zone listing].

See xref:how-to/choose-node-class.adoc[] on how to schedule your workload on a specific node class.

You will find the characteristics of all node classes explained below.

== cloudscale.ch Zones

flex::
+
Flex nodes directly map to https://www.cloudscale.ch/en/pricing#flavors-explained[flex instances defined by the infrastructure provider].
They use CPUs shared with other instances.
This allows for short-term load peaks but can occasionally require your workload to wait for CPU time.
Workload running on Flex nodes will cost you less (see https://products.docs.vshn.ch/products/appuio/cloud/pricing.html[pricing]).
+
Use this node class for your background jobs, test environments or applications not sensitive to latency.
+
On an {product} zone running on cloudscale.ch, your workload will by default be scheduled on flex nodes.

plus::
+
Plus nodes directly map to https://www.cloudscale.ch/en/pricing#flavors-explained[plus instances defined by the infrastructure provider].
Plus nodes have dedicated CPU cores.
This gives you consistent performance but will cost you more (see https://products.docs.vshn.ch/products/appuio/cloud/pricing.html[pricing]).
+
The plus node class is probably the right choice for your production frontends, database and other applications sensitive to latency.

night::
+
Night nodes are plus nodes where workload interruptions during (European) office hours are limited as much as possible.
Regular node maintenance and any other non-emergency node changes are carried out after 22:00 (CET/CEST).
Night maintenance comes at a premium (see https://products.docs.vshn.ch/products/appuio/cloud/pricing.html[pricing]).
+
Night nodes are useful for production applications that require minimal downtime but can't be run with multiple replicas in high availability (HA) fashion.
