= Getting Started on {product} with the OpenShift Web Console using F#

image:logos/fsharp.svg[role="related thumb right",alt="Programming language logo",width=120,height=120] This tutorial explains how to run applications written in the F# programming language on {product} using the OpenShift web console.

If you would rather use the command line, you might want to try the xref:tutorials/getting-started/fsharp-terminal.adoc[Getting Started with F# on the Terminal] guide instead.

== Requirements

This tutorial doesn't require anything else than an {product} account and a modern web browser with JavaScript enabled.

== About the Application

To demo how to run applications written in the https://fsharp.org/[F#] programming language on {product}, we will use a small demo application using the https://giraffe.wiki/[Giraffe Framework], bundled as a container thanks to its corresponding `Dockerfile`, and ready to be used on {product}.

The "Fortune in F#" application does one simple thing: when invoked on the browser, it returns a random number and a funny quote. That's all!

You can browse the full source code of this application on GitLab: https://gitlab.com/vshn/applications/fortune-fsharp

== Step 1: Create an OpenShift Project

Follow these steps to create an OpenShift project and deploy the application:

. Login to {product} and open the "Developer" perspective.
. Create a new project called "fortune-fsharp."
. Switch to the "Developer" perspective.
. Click the "+Add" button on the sidebar.
. Select the "Container images" option.
+
IMPORTANT: As explained in xref:explanation/differences-to-public.adoc[this page], not all options in this screen are available in {product}. In particular, it's not possible to choose the "Import from Git" option, as this requires image building capabilities that aren't yet available in {product}.

. In the "Image name from external registry" field, enter the URL of the Fortune in F# container:
** `registry.gitlab.com/vshn/applications/fortune-fsharp:latest`
. Change the runtime icon to match the F# programming language or the Giraffe Framework framework (if available).
. Scroll down and uncheck the "Create a route to the Application" checkbox.
. Click "Create."
. After a few seconds, you will see in the "Topology" section an icon representing the Fortune in F# application running. If you click on it, you will see that there is no route to access the object.

== Step 2: Publish your Application

At the moment your container is running but it's not available from the Internet. To be able to access our application, we must create an `Ingress` object.

. Switch to the "Developer" perspective.
. Click the "+Add" button on the sidebar.
. Select the "From Local Machine–Import YAML" option
. Paste and customize the code below in the editor:
+
[source,yaml]
--
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: fortune-fsharp-ingress
  namespace: fortune-fsharp # <1>
spec:
  rules:
  - host: [YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud # <2>
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: fortune-fsharp
            port:
              number: 8080
  tls:
  - hosts:
    - [YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud
    secretName: fortune-fsharp-cert
--
<1> Make sure this annotation matches exactly the name of your project: `fortune-fsharp`
<2> Replace the placeholders `YOUR_APP_NAME` and `YOUR_PREFERRED_ZONE` with valid values.

. Click the "Create" button.
. After a few seconds, go back to the "Topology" screen, and select your container. You should see a "Routes" field now, with the clickable URL `http://[YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud`, displaying your daily fortune cookie message!

== Step 3: There's no Step 3!

The "Fortune in  F#" application is now running on {product}. Congratulations!

What's next? To run your own application written in F# or using the Giraffe Framework application on {product}, follow these steps:

* Containerize the application making sure it's compatible with {product}. The `Dockerfile` above can serve as a starting point.
* Create a deployment (in YAML format) for your application, or better yet, a https://helm.sh/[Helm] chart.
* Configure your CI/CD system to automatically deploy your application to your cluster.
* When you're done testing the fortune application, you can open the "Projects" menu in the "Administrator" perspective to delete the `fortune-fsharp` project.