= Getting Started on {product} with the Terminal using Kotlin

image:logos/kotlin.svg[role="related thumb right",alt="Programming language logo",width=120,height=120] This tutorial explains how to run applications written in the Kotlin programming language on {product} using the command line.

If you aren't familiar with issuing commands on a terminal session, you might want to try the xref:tutorials/getting-started/kotlin-web.adoc[Getting Started with Kotlin on the OpenShift Web Console] guide instead.

== Requirements

To follow this guide, please make sure that you have the following tools installed:

A web browser:: Google Chrome, Firefox, Microsoft Edge, Safari, or Opera, with JavaScript enabled.

`oc`:: You can download the OpenShift command directly from {product}, selecting the help menu (marked as a question mark) and selecting the "Command line tools" entry.

`docker` or `podman`:: You can download them from https://www.docker.com and https://podman.io.

`curl`:: Available from https://curl.se.

== About the Application

To demo how to run applications written in the https://kotlinlang.org/[Kotlin] programming language on {product}, we will use a small demo application using the https://ktor.io/[Ktor Framework], bundled as a container thanks to its corresponding `Dockerfile`, and ready to be used on {product}.

You can browse the full source code of this application on GitLab: https://gitlab.com/vshn/applications/fortune-kotlin

The "Fortune in Kotlin" application does a few simple things:

* When invoked on the browser, it returns a random number and a funny quote.
* When invoked with an HTTP request including the `Accept: application/json` header, it returns the same information in JSON format.
* Finally, when invoked with an HTTP request including the `Accept: text/plain` header, it returns the same information in plain text format.

Learn more about the `fortune-kotlin` application, including how to edit and build it, on the https://gitlab.com/vshn/applications/fortune-kotlin/-/blob/master/README.adoc[project README].

=== The Router

The code below shows the main router of the application in the Kotlin programming language, located at https://gitlab.com/vshn/applications/fortune-kotlin/-/blob/master/src/main/kotlin/cloud/appuio/plugins/Routing.kt[src/main/kotlin/cloud/appuio/plugins/Routing.kt], courtesy of the https://ktor.io/[Ktor Framework].

[source,kotlin,indent=0]
--
fun Application.configureRouting() {
    install(Mustache) {
        mustacheFactory = DefaultMustacheFactory("templates")
    }
    install(ContentNegotiation) {
        gson()
    }

    routing {
        get("/") {
            val fortune = Fortune((1..1000).random(),
                                  "fortune".runCommand(),
                                  "1.0-kotlin",
                                  "hostname".runCommand())
            val accept = call.request.accept() ?: ""
            val text = """Fortune ${fortune.version} cookie of the day ${fortune.number}:

${fortune.message}
Pod: ${fortune.hostname}"""

            when (accept) {
                "application/json" -> call.respond(fortune)
                "text/plain" -> call.respondText(text)
                else -> call.respond(MustacheContent("fortune.hbs", mapOf("fortune" to fortune)))
            }
        }
    }
}
--

=== Run the Container

This step is optional; you can easily test the application locally with Docker or Podman:

[source,shell]
--
$ docker run --rm --publish 8080:8080 registry.gitlab.com/vshn/applications/fortune-kotlin:latest
$ podman run --rm --publish 8080:8080 registry.gitlab.com/vshn/applications/fortune-kotlin:latest
--

Now you can test the application with `curl`:

[source,shell]
--
$ curl http://localhost:8080 --header "Accept: application/json"
$ curl http://localhost:8080 --header "Accept: text/plain"
--

You can also open a browser and navigate to http://localhost:8080 to get your fortune cookie of the day.

=== Dockerfile

The application includes a https://gitlab.com/vshn/applications/fortune-kotlin/-/blob/master/Dockerfile[Dockerfile] ready to build a container fully compatible with OpenShift. The snippet below shows the instructions used to build the actual running image:

[source,dockerfile,indent=0]
--
# Step 2: Runtime
FROM openjdk:8-jre-alpine

RUN apk add --no-cache fortune
RUN mkdir /app
RUN chown -R 1001:0 /app
RUN chmod -R 755 /app
COPY --from=build /appbuild/build/libs/cloud.appuio.fortune-kotlin*all.jar /app/cloud.appuio.fortune-kotlin.jar
WORKDIR /app

EXPOSE 8080

# <1>
USER 1001:0

CMD ["sh", "-c", "java -server -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:InitialRAMFraction=2 -XX:MinRAMFraction=2 -XX:MaxRAMFraction=2 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -jar cloud.appuio.fortune-kotlin.jar"]
--
<1> This explicitly prevents the container from running as root; this is a requirement of OpenShift, and a good practice for images in general.

You can use the `Dockerfile` above to build your own copy of the container, which you can then push to the registry of your choice:

[source,shell]
--
$ git clone https://gitlab.com/vshn/applications/fortune-kotlin.git
$ cd fortune-kotlin
$ docker build -t fortune-kotlin .
$ podman build -t fortune-kotlin .
--

== Step 1: Create a Project

Follow these steps to login to {product} on your terminal, create a project, and to deploy the application:

. Login to the {product} console with your web browser.
. Click on your user name on the top right and select "Copy login command"
. Click "Display token" and copy the login command shown in "Log in with this token"
. Paste the `oc login` command on the terminal:
+
[source,shell]
--
$ oc login --token=sha256~_xxxxxx_xxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxx-X --server=https://api.[YOUR_PREFERRED_ZONE].appuio.cloud:6443
$ oc projects
You aren't a member of any projects. You can request a project to be created with the 'new-project' command.
--

. Create a new project called "fortune-kotlin"
+
[source,shell]
--
$ oc new-project fortune-kotlin
Now using project "fortune-kotlin" on server "https://api.[YOUR_PREFERRED_ZONE].appuio.cloud:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.io/serve_hostname
--

. To deploy the application we will use a standard Kubernetes `Deployment` object. Save the following YAML in a file called `deployment.yaml`:
+
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-kotlin
  namespace: fortune-kotlin # <1>
  labels:
    app: fortune-kotlin
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitlab-pull-secret
      containers:
      - image: registry.gitlab.com/vshn/applications/fortune-kotlin:latest
        imagePullPolicy: Always
        name: fortune-container
        ports:
        - containerPort: 8080
    metadata:
      labels:
        app: fortune-kotlin
  selector:
    matchLabels:
      app: fortune-kotlin
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-kotlin
  namespace: fortune-kotlin # <1>
  labels:
    app: fortune-kotlin
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: fortune-kotlin
  type: ClusterIP
----
<1> Make sure this annotation matches exactly the name of your project: `fortune-kotlin`

. Then apply the deployment to your {product} project and wait until your pod appears with the status "Running":
+
[source,shell]
--
$ oc -n fortune-kotlin apply -f deployment.yaml
deployment.apps/fortune-kotlin created
service/fortune-kotlin created
$ oc -n fortune-kotlin get pods --watch
NAME                         READY   STATUS    RESTARTS   AGE
fortune-kotlin-6fbd5484cf-k47gt   1/1     Running   0          11s
--

== Step 2: Publish your Application

At the moment your container is running but it's not available from the Internet. To be able to access our application, we must create an `Ingress` object.

. Create another file called `ingress.yaml` with the following contents, customizing the parts marked as `[YOUR_APP_NAME]` and `[YOUR_PREFERRED_ZONE]` to your liking:
+
[source,yaml]
--
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: fortune-kotlin-ingress
  namespace: fortune-kotlin # <1>
spec:
  rules:
  - host: [YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud # <2>
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: fortune-kotlin
            port:
              number: 8080
  tls:
  - hosts:
    - [YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud
    secretName: fortune-kotlin-cert
--
<1> Make sure this annotation matches exactly the name of your project: `fortune-kotlin`
<2> Replace the placeholders `YOUR_APP_NAME` and `YOUR_PREFERRED_ZONE` with valid values.

. Apply the ingress object to your {product} project and wait until you route shows as available.
+
[source,shell]
--
$ oc -n fortune-kotlin apply -f ingress.yaml
ingress.networking.k8s.io/fortune-kotlin-ingress created
$ oc -n fortune-kotlin get routes --watch
NAME                      HOST/PORT                                         PATH   SERVICES    PORT    TERMINATION     WILDCARD
fortune-kotlin-ingress-4pk2j   fortune-kotlin.apps.[YOUR_PREFERRED_ZONE].appuio.cloud   /      fortune-kotlin   <all>   edge/Redirect   None
--

. After a few seconds, you should be able to get your daily fortune message using `curl`!
+
[source,shell]
--
$ curl https://[YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud --header "Accept: text/plain"
$ curl https://[YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud --header "Accept: application/json"
--

== Step 3: There's no Step 3!

The "Fortune in  Kotlin" application is now running on {product}. Congratulations!

What's next? To run your own application written in Kotlin or using the Ktor Framework application on {product}, follow these steps:

* Containerize the application making sure it's compatible with {product}. The `Dockerfile` above can serve as a starting point.
* Enhance the deployment for your application with liveness and health probes, or better yet, create a https://helm.sh/[Helm] chart.
* Configure your CI/CD system to automatically deploy your application to your cluster.
* When you're done testing the fortune application, delete the `fortune-kotlin` project with the following command:
+
[source,shell]
--
$ oc delete project fortune-kotlin
--