= Getting Started on {product} with the Terminal using PHP

image:logos/php.svg[role="related thumb right",alt="Programming language logo",width=120,height=120] This tutorial explains how to run applications written in the PHP programming language on {product} using the command line.

If you aren't familiar with issuing commands on a terminal session, you might want to try the xref:tutorials/getting-started/php-web.adoc[Getting Started with PHP on the OpenShift Web Console] guide instead.

== Requirements

To follow this guide, please make sure that you have the following tools installed:

A web browser:: Google Chrome, Firefox, Microsoft Edge, Safari, or Opera, with JavaScript enabled.

`oc`:: You can download the OpenShift command directly from {product}, selecting the help menu (marked as a question mark) and selecting the "Command line tools" entry.

`docker` or `podman`:: You can download them from https://www.docker.com and https://podman.io.

`curl`:: Available from https://curl.se.

== About the Application

To demo how to run applications written in the https://www.php.net/[PHP] programming language on {product}, we will use a small demo application using the https://www.slimframework.com/[Slim Framework], bundled as a container thanks to its corresponding `Dockerfile`, and ready to be used on {product}.

You can browse the full source code of this application on GitLab: https://gitlab.com/vshn/applications/fortune-php

The "Fortune in PHP" application does a few simple things:

* When invoked on the browser, it returns a random number and a funny quote.
* When invoked with an HTTP request including the `Accept: application/json` header, it returns the same information in JSON format.
* Finally, when invoked with an HTTP request including the `Accept: text/plain` header, it returns the same information in plain text format.

Learn more about the `fortune-php` application, including how to edit and build it, on the https://gitlab.com/vshn/applications/fortune-php/-/blob/master/README.adoc[project README].

=== The Router

The code below shows the main router of the application in the PHP programming language, located at https://gitlab.com/vshn/applications/fortune-php/-/blob/master/public/index.php[public/index.php], courtesy of the https://www.slimframework.com/[Slim Framework].

[source,php,indent=0]
--
$app->get('/', function (Request $request, Response $response, $args) {
    $data = [
        'message' => `fortune`,
        'number' => rand(1, 1000),
        'version' => '1.0-php',
        'hostname' => `hostname`
    ];
    if ($request->hasHeader('Accept')) {
        $acceptHeader = $request->getHeaderLine('Accept');
        if ($acceptHeader === 'application/json') {
            $json = json_encode($data);
            $response->getBody()->write($json);
            return $response->withHeader('Content-Type', 'application/json');
        }
        if ($acceptHeader === 'text/plain') {
            $format = "Fortune %s cookie of the day #%d:\n\n%s";
            $result = sprintf($format, $data['version'], $data['number'], $data['message']);
            $response->getBody()->write($result);
            return $response->withHeader('Content-Type', 'text/plain');
        }
    }
    $view = Twig::fromRequest($request);
    return $view->render($response, 'fortune.html', $data);
});

$app->run();
--

=== Run the Container

This step is optional; you can easily test the application locally with Docker or Podman:

[source,shell]
--
$ docker run --rm --publish 8080:8080 registry.gitlab.com/vshn/applications/fortune-php:latest
$ podman run --rm --publish 8080:8080 registry.gitlab.com/vshn/applications/fortune-php:latest
--

Now you can test the application with `curl`:

[source,shell]
--
$ curl http://localhost:8080 --header "Accept: application/json"
$ curl http://localhost:8080 --header "Accept: text/plain"
--

You can also open a browser and navigate to http://localhost:8080 to get your fortune cookie of the day.

=== Dockerfile

The application includes a https://gitlab.com/vshn/applications/fortune-php/-/blob/master/Dockerfile[Dockerfile] ready to build a container fully compatible with OpenShift. The snippet below shows the instructions used to build the actual running image:

[source,dockerfile,indent=0]
--
# Step 2: Production image
# Adapted from
# https://github.com/TrafeX/docker-php-nginx
FROM alpine:3.14

# Install packages and remove default server definition
RUN apk --no-cache add \
  fortune \
  nginx \
  php8 \
  php8-fpm \
  php8-json \
  supervisor

# Create symlink so programs depending on `php` still function
RUN ln -s /usr/bin/php8 /usr/bin/php

# Configure nginx
COPY config/nginx.conf /etc/nginx/nginx.conf

# Configure PHP-FPM
COPY config/fpm-pool.conf /etc/php8/php-fpm.d/www.conf
COPY config/php.ini /etc/php8/conf.d/custom.ini

# Configure supervisord
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Setup document root
RUN mkdir -p /var/www/html
RUN mkdir -p /run/
RUN mkdir -p /var/cache/nginx

# The following lines make this image compatible with OpenShift.
# Source: https://torstenwalter.de/openshift/nginx/2017/08/04/nginx-on-openshift.html
RUN \
    # support running as arbitrary user which belongs to the root group
    chmod g+rwx /var/cache/nginx /run /var/log/nginx && \
    # comment user directive as master process is run as different user anyhow
    sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf

# Add application
WORKDIR /var/www/html
COPY --chown=1001:0 templates /var/www/html/templates
COPY --chown=1001:0 public /var/www/html/public
COPY --from=composer --chown=1001:0 /app/vendor /var/www/html/vendor

# Make sure files/folders needed by the processes are accessable when they run under a non-root user
RUN chown -R 1001:0 /var/www/html && \
  chown -R 1001:0 /run && \
  chown -R 1001:0 /var/lib/nginx && \
  chown -R 1001:0 /var/log/nginx

# Expose the port nginx is reachable on
EXPOSE 8080

# Switch to use a non-root user from here on
# <1>
USER 1001:0

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
--
<1> This explicitly prevents the container from running as root; this is a requirement of OpenShift, and a good practice for images in general.

You can use the `Dockerfile` above to build your own copy of the container, which you can then push to the registry of your choice:

[source,shell]
--
$ git clone https://gitlab.com/vshn/applications/fortune-php.git
$ cd fortune-php
$ docker build -t fortune-php .
$ podman build -t fortune-php .
--

== Step 1: Create a Project

Follow these steps to login to {product} on your terminal, create a project, and to deploy the application:

. Login to the {product} console with your web browser.
. Click on your user name on the top right and select "Copy login command"
. Click "Display token" and copy the login command shown in "Log in with this token"
. Paste the `oc login` command on the terminal:
+
[source,shell]
--
$ oc login --token=sha256~_xxxxxx_xxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxx-X --server=https://api.[YOUR_PREFERRED_ZONE].appuio.cloud:6443
$ oc projects
You aren't a member of any projects. You can request a project to be created with the 'new-project' command.
--

. Create a new project called "fortune-php"
+
[source,shell]
--
$ oc new-project fortune-php
Now using project "fortune-php" on server "https://api.[YOUR_PREFERRED_ZONE].appuio.cloud:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.io/serve_hostname
--

. To deploy the application we will use a standard Kubernetes `Deployment` object. Save the following YAML in a file called `deployment.yaml`:
+
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-php
  namespace: fortune-php # <1>
  labels:
    app: fortune-php
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gitlab-pull-secret
      containers:
      - image: registry.gitlab.com/vshn/applications/fortune-php:latest
        imagePullPolicy: Always
        name: fortune-container
        ports:
        - containerPort: 8080
    metadata:
      labels:
        app: fortune-php
  selector:
    matchLabels:
      app: fortune-php
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-php
  namespace: fortune-php # <1>
  labels:
    app: fortune-php
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: fortune-php
  type: ClusterIP
----
<1> Make sure this annotation matches exactly the name of your project: `fortune-php`

. Then apply the deployment to your {product} project and wait until your pod appears with the status "Running":
+
[source,shell]
--
$ oc -n fortune-php apply -f deployment.yaml
deployment.apps/fortune-php created
service/fortune-php created
$ oc -n fortune-php get pods --watch
NAME                         READY   STATUS    RESTARTS   AGE
fortune-php-6fbd5484cf-k47gt   1/1     Running   0          11s
--

== Step 2: Publish your Application

At the moment your container is running but it's not available from the Internet. To be able to access our application, we must create an `Ingress` object.

. Create another file called `ingress.yaml` with the following contents, customizing the parts marked as `[YOUR_APP_NAME]` and `[YOUR_PREFERRED_ZONE]` to your liking:
+
[source,yaml]
--
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: fortune-php-ingress
  namespace: fortune-php # <1>
spec:
  rules:
  - host: [YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud # <2>
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: fortune-php
            port:
              number: 8080
  tls:
  - hosts:
    - [YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud
    secretName: fortune-php-cert
--
<1> Make sure this annotation matches exactly the name of your project: `fortune-php`
<2> Replace the placeholders `YOUR_APP_NAME` and `YOUR_PREFERRED_ZONE` with valid values.

. Apply the ingress object to your {product} project and wait until you route shows as available.
+
[source,shell]
--
$ oc -n fortune-php apply -f ingress.yaml
ingress.networking.k8s.io/fortune-php-ingress created
$ oc -n fortune-php get routes --watch
NAME                      HOST/PORT                                         PATH   SERVICES    PORT    TERMINATION     WILDCARD
fortune-php-ingress-4pk2j   fortune-php.apps.[YOUR_PREFERRED_ZONE].appuio.cloud   /      fortune-php   <all>   edge/Redirect   None
--

. After a few seconds, you should be able to get your daily fortune message using `curl`!
+
[source,shell]
--
$ curl https://[YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud --header "Accept: text/plain"
$ curl https://[YOUR_APP_NAME].apps.[YOUR_PREFERRED_ZONE].appuio.cloud --header "Accept: application/json"
--

== Step 3: There's no Step 3!

The "Fortune in  PHP" application is now running on {product}. Congratulations!

What's next? To run your own application written in PHP or using the Slim Framework application on {product}, follow these steps:

* Containerize the application making sure it's compatible with {product}. The `Dockerfile` above can serve as a starting point.
* Enhance the deployment for your application with liveness and health probes, or better yet, create a https://helm.sh/[Helm] chart.
* Configure your CI/CD system to automatically deploy your application to your cluster.
* When you're done testing the fortune application, delete the `fortune-php` project with the following command:
+
[source,shell]
--
$ oc delete project fortune-php
--