= Getting Started on {product} with the OpenShift Web Console using Rust

image:logos/rust.svg[role="related thumb right",alt="Programming language logo",width=120,height=120] This tutorial explains how to run applications written in the Rust programming language on {product} using the OpenShift web console.

If you would rather use the command line, you might want to try the xref:tutorials/getting-started/rust-terminal.adoc[Getting Started with Rust on the Terminal] guide instead.

== Requirements

This tutorial doesn't require anything else than an {product} account and a modern web browser with JavaScript enabled.

== About the Application

To demo how to run applications written in the https://www.rust-lang.org/[Rust] programming language on {product}, we will use a small demo application using the https://actix.rs/[Actix Framework], bundled as a container thanks to its corresponding `Dockerfile`, and ready to be used on {product}.

The "Fortune in Rust" application does one simple thing: when invoked on the browser, it returns a random number and a funny quote. That's all!

You can browse the full source code of this application on GitLab: https://gitlab.com/vshn/applications/fortune-rust

== Step 1: Deploy a Container

Follow these steps to create an OpenShift project and deploy the application:

. Login to {product} and open the "Developer" perspective.
. Create a new project called "fortune-rust."
. Switch to the "Developer" perspective.
. Click the "+Add" button on the sidebar.
. Select the "Container images" option.
+
IMPORTANT: As explained in xref:explanation/differences-to-public.adoc[this page], not all options in this screen are available in {product}. In particular, it's not possible to choose the "Import from Git" option, as this requires image building capabilities that aren't yet available in {product}.

. In the "Image name from external registry" field, enter the URL of the Fortune in Rust container:
** `registry.gitlab.com/vshn/applications/fortune-rust:latest`
. Change the runtime icon to match the Rust programming language or the Actix Framework (if available).
. Click "Create."
. After a few seconds, you will see in the "Topology" section an icon representing the "Fortune in Rust" application running. If you click on it, you will see that there is a "Route" to access the object; it will contain a clickable URL similar to `http://fortune-rust-fortune-rust.apps.[YOUR_PREFERRED_ZONE].appuio.cloud`, and if you click on it, you will see your daily fortune cookie message!

== Step 2: There's no Step 2!

The "Fortune in  Rust" application is now running on {product}. Congratulations!

What's next? To run your own application written in Rust or using the Actix Framework on {product}, follow these steps:

* Check the xref:tutorials/getting-started/rust-terminal.adoc[Getting Started with Rust on the Terminal] guide for more technical information.
* Make sure your CI/CD system is ready to automatically deploy your application to your cluster.

Finally, when you're done testing the fortune application, you can open the "Projects" menu in the "Administrator" perspective and delete the `fortune-rust` project, by selecting the appropriate entry on the "Actions" menu.